version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3005
    volumes: 
      - .:/usr/src/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
  mysql_server:
    image: mysql
    container_name: dbc-mysql
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./sql_scripts:/docker-entrypoint-initdb.d/
    environment: 
      MYSQL_ROOT_PASSWORD: docker
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080  